apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: data-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
