apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: data-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: data-jobs
rules:
  - apiGroups: [""]
    resources: ["pods","services","configmaps","persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/log","pods/exec"]
    verbs: ["get","list","create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: data-jobs
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: data-jobs
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
