apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-platform-hive-metastore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amekala2514/platform-lab-gitops
    targetRevision: main
    path: workloads/data-platform/hive-metastore
  destination:
    server: https://kubernetes.default.svc
    namespace: data-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
