apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-platform-spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: 2.0.2
    helm:
      releaseName: spark-operator
      values: |
        controller:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        webhook:
          enable: true
          replicas: 1
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        spark:
          jobNamespaces:
            - data-jobs
        prometheus:
          metrics:
            enable: true
          podMonitor:
            create: true
            labels:
              release: kps
  destination:
    server: https://kubernetes.default.svc
    namespace: data-jobs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
