apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-platform-event-generator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amekala2514/platform-lab-gitops.git
    targetRevision: HEAD
    path: workloads/data-platform/event-generator
  destination:
    server: https://kubernetes.default.svc
    namespace: data-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
