apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-api-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amekala2514/platform-lab-gitops.git
    targetRevision: main
    path: workloads/platform-api
    directory:
      recurse: false
      include: 'servicemonitor.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
